### ISSUE TITLE
How do I install the prerequisites?

### ISSUE THREAD

**Issue by AnthonyMastrean** [hercules-team/augeasproviders_core#13]
Your [website](http://augeasproviders.com/setup/) and [forge documentation](https://forge.puppet.com/herculesteam/augeasproviders_core/readme) both say to install Augeas and the Ruby bindings. The link to the Puppet/Augeas docs reference a non-existing "pre-requisites" section. As-is, I'm unable to figure out both _what_ to install or _how_ to install it.

> **Requirements**
> 
> Ensure both Augeas and ruby-augeas 0.3.0+ bindings are installed and working as normal.
> 
> See [Puppet/Augeas pre-requisites](https://puppet.com/docs/puppet/6.0/resources_augeas.html#pre-requisites).

The Puppet [augeas_core documentation](https://forge.puppet.com/puppetlabs/augeas_core#setup-requirements) says everything should already be installed? But, that's not what I'm seeing when I try to use the `sysctl` resource (for example).

> The augeas libraries and ruby bindings must be installed in order to use this module. If you are using puppet-agent packages, then those prerequisites are already satisfied for most platforms.

I don't want to manually install anything except Puppet on this box, so I'm not going to run `yum install augeas`.

I don't have a system Ruby installed, although Puppet vendors one, but I don't think I'm supposed to use it directly. And I'm not going to run `gem install ruby-augeas`. That [gem](https://rubygems.org/gems/ruby-augeas) is pre-release and it's not been updated for many years.

**Comment by AnthonyMastrean** [comment]
OK, I must be having a bad day (or Windows & Git are conspiring to destroy line-endings again). When I run everything manually from _inside_ a VM, it looks fine.

```
[vagrant@localhost ~]$ sudo -i puppet module install herculesteam-augeasproviders_sysctl --version 2.2.1
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppet.com ...
Notice: Installing -- do not interrupt ...
/etc/puppetlabs/code/environments/production/modules
└─┬ herculesteam-augeasproviders_sysctl (v2.2.1)
  └─┬ herculesteam-augeasproviders_core (v2.2.0)
    └── puppetlabs-stdlib (v5.1.0)
[vagrant@localhost ~]$ sysctl net.ipv4.ip_forward
net.ipv4.ip_forward = 1
[vagrant@localhost ~]$ sudo -i puppet apply -e 'sysctl { "net.ipv4.ip_forward": ensure => present, value => 1 }'
Notice: Compiled catalog for localhost.localdomain in environment production in 0.04 seconds
Notice: /Stage[main]/Main/Sysctl[net.ipv4.ip_forward]/value: changed configuration value from '' to '1'
Notice: Applied catalog in 0.17 seconds
[vagrant@localhost ~]$ sysctl net.ipv4.ip_forward
net.ipv4.ip_forward = 1
[vagrant@localhost ~]$ sudo -i puppet apply -e 'sysctl { "net.ipv4.ip_forward": ensure => present, value => 1 }'
Notice: Compiled catalog for localhost.localdomain in environment production in 0.04 seconds
Notice: Applied catalog in 0.14 seconds
```

I'll scrutinize my production workflow to see what's going haywire!

**Comment by raphink** [comment]
Good to know it actually works. By the way, you don't need to use  `puppet apply` to test single resources, you can use `puppet resource` for that, e.g.:

```
sudo puppet resource sysctl net.ipv4.ip_forward ensure=present value=1
```
