### ISSUE TITLE
Error while installing puppet module camptocamp/openldap 1.14.0

### ISSUE THREAD

**Issue by raja5674** [hercules-team/augeasproviders_core#14]
Hello Team,

I am getting the below error while installing puppet module.

Puppet Module: (puppet version is 3.7.4)
-----------------
puppet module install puppetlabs/postgresql --version 4.7.1
puppet module install camptocamp/openldap --version 1.14.0
puppet module install puppetlabs/firewall --version 1.8.0

Error: /Stage[main]/Openldap::Server::Config/Shellvar[SLAPD_LDAPS]: Could not evaluate: undefined method ‘context=’ for # (Augeas: 0x7f4609926390)
Error: /Stage[main]/Openldap::Server::Config/Shellvar[SLAPD_LDAP]: Could not evaluate: undefined method ‘context=’ for # (Augeas: 0x7f4609926390)

Please help me to resolve this issue. what could be the problem. 

Thanks,
Raja Rajagopal

**Comment by raphink** [comment]
Are you using the AIO package for Puppet, or your distribution's version?

**Comment by raja5674** [comment]
Hello,

Thanks for the reply. However, I did not get to understand your questions. So, we are using Vagrant file to install puppet modules. Like I will issue "vagrant up" command from my project. The project contains the vagrant file and internally it will call a script. That script has below command to execute.

puppet module install puppetlabs/postgresql --version 4.7.1 - This is installing successfully.

puppet module install camptocamp/openldap --version 1.14.0  -when this command getting executed, getting the above error.

Please let me know if you any clue to overcome this issue.

Thanks,
Raja Rajagopal

**Comment by raphink** [comment]
My question was about how Puppet (and `ruby-augeas`) is installed on your Vagrant boxes. Is it installed using the official (AIO) packages from Puppet Inc, using the packages from your distribution, or using Rubygems?

**Comment by raja5674** [comment]
Hello,

Thanks for the reply.
I think puppet got installed through RubyGems. I guess, the following command in my vagrant file will install puppet on my vagrant boxes.
config.vm.box = "puppetlabs/centos-6.6-64-puppet"

Sorry, I could not attach the files. It is not allowing me to attach the file.

GemFile Content: 
source "https://rubygems.org"
gem "rake"
gem "puppet", ENV['PUPPET_VERSION'] || '~> 3.7.0'
gem "rspec-puppet"
gem "metadata-json-lint"
gem "puppet-lint"
gem "puppetlabs_spec_helper"

Some lines from my Vagrant file:
  #
  # Install required Puppet modules
  #
  config.vm.provision :shell do |script|
    script.path = "provisioners/install-puppet-modules.sh"
    script.binary = true
  end

config.vm.provision :puppet, manifests_path: "puppet/manifests", manifest_file: "site.pp", module_path: "puppet/modules"
end

Please let me know, if you need any more information and I will try to provide the same.

Note: Some of my colleagues used the same vagrant file and for them installed successfully.

Thanks,
Raja Rajagopal

**Comment by raphink** [comment]
What version of the Augeas gem are you using then? Are you using the `ruby-augeas` or `augeas` gem?

**Comment by raja5674** [comment]
Hello,

Thanks for the reply.
I really do not know about Augeas gem version which I am using and ruby-augeas . 

All I did was I run the "Vagrant file" which is available in our project and it installed all the required softwares/modules in the VM. 

Do you want me paste the content of my vagrant file.? Please let me know, I will do the same.

Here is some of the details while doing vagrant up command:

Notice: Preparing to install into /etc/puppet/modules ...
Notice: Downloding from https://forgeapi.puppetlabs.com ....
Notice: Installing - do not interrupt ...
default: /etc/puppet/modules
            camptocamp-openladap (v1.14.0)
                 hercluesteam-augeasproviders_shellvar (v2.2.4)
                      hercluesteam-augeasproviders_core (v2.4.0) 
                         puppetlabs-stdlib (v2.45.1)

etc...

Note: I am using a Vagrant base box from a 3rd party. Like I mentioned above I am using 
puppetlabs/centos-6.6-64-puppet Vagrant box.

Thanks,
Raja Rajagopal

**Comment by raphink** [comment]
Can you run `sudo gem list` in your vagrant box?

**Comment by raja5674** [comment]
Thanks for the reply.
Here is the output of 'sudo gem list'

[vagrant@target puppet]$ sudo gem list

*** LOCAL GEMS ***

json (1.5.5)

Thanks,
Raja Rajagopal

**Comment by raphink** [comment]
OK. I'm sorry, I can't help you debug your Vagrant box. You need to find out what is the Augeas gem installed in the environment where Puppet is launched. It should be `ruby-augeas`, but I suspect you actually have `augeas` instead. Could you check with the people providing the Vagrantfile?

**Comment by raja5674** [comment]
Hello Raphink,

I am opening this ticket again with some inputs. Here is the GEM installation details. Could you please let me know with this details, Shall I find the root cause of the problem. 
[vagrant@target json-1.5.5]$ gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 1.3.7
  - RUBY VERSION: 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/lib/ruby/gems/1.8
  - RUBY EXECUTABLE: /usr/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/lib/ruby/gems/1.8
     - /home/vagrant/.gem/ruby/1.8
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :benchmark => false
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - http://rubygems.org/

Please let me know if you need any details.

Thanks,
Raja Rajagopal

**Comment by raja5674** [comment]
Hello Team,
I would like to provide some more difference between my in my installation and my colleague installation was,
In my system the installation was:
Notice: Installing -- do not interrupt ...
    default: /etc/puppet/modules
    default: └─┬ camptocamp-openldap (v1.14.0)
    default:   ├─┬ herculesteam-augeasproviders_core (v2.2.0)
    default:   │ └── puppetlabs-stdlib (v4.25.1)
    default:   └── herculesteam-augeasproviders_shellvar (v2.2.4)

My colleague installation is,
INFO interface: detail:     default: /etc/puppet/modules
   default: └─┬ camptocamp-openldap (v1.14.0)
   default:   ├─┬ herculesteam-augeasproviders_shellvar (v2.2.4)
   default:   │ └── herculesteam-augeasproviders_core (v2.4.0)
   default:   └── puppetlabs-stdlib (v4.25.1)

I could see the difference in "herculesteam-augeasproviders_core". I do not have any idea, How to downgrade to 2.2.0. Appreciate if you could help me on this. 

Thanks,
Raja

**Comment by raja5674** [comment]
Hello Team,

Thanks for the support. we have resolved the issue by installing herculesteam-augeasproviders_core (v2.2.0) version separately.
